### ISSUE TITLE
add apkcombo.com

### ISSUE THREAD

**Issue by luweitest** [gfwlist/gfwlist#1901] opened 2020-02-24 07:46 UTC
please verify.

**Comment by gundaz-aghayev** [comment] 2020-09-25 11:06
DNS + SNI

**Comment by s7lx** [comment] 2022-05-12 07:57
DNS pollution

ISP: Aliyun Shanghai

**Comment by s7lx** [comment] 2022-05-12 07:58
solved

**Comment by cicku** [comment] 2023-01-09 03:58
Duplicate of #2026

**Closed by cicku** 2023-01-09 03:58 UTC
Labels: DUPLICATE
