### ISSUE TITLE
Add hackmd.io

### ISSUE THREAD

**Issue by zt2** [gfwlist/gfwlist#1681] opened 2019-08-28 16:01 UTC
Please add hackmd.io to gfwlist

**Comment by cairenbin** [comment] 2019-09-11 03:52
> Please add hackmd.io to gfwlist

I reported it half year ago

[https://github.com/gfwlist/gfwlist/issues/1472](url)

**Comment by cicku** [comment] 2021-04-19 23:14
Duplicate of #1472

**Closed by cicku** 2021-04-19 23:14 UTC
Labels: DUPLICATE
