### ISSUE TITLE
Please add 'reddit.com'

### ISSUE THREAD

**Issue by cym104** [gfwlist/gfwlist#1327] opened 2018-11-20 11:59 UTC
Surprised no one mentioned this yet.

**Comment by paperbag** [comment] 2018-11-21 08:34
> Surprised no one mentioned this yet.

https://github.com/gfwlist/gfwlist/issues/1173

**Comment by cicku** [comment] 2018-11-24 04:12
Surprised you are the only one still mentions it...

Duplicate of #1173

**Closed by cicku** 2018-11-24 04:12 UTC
Labels: DUPLICATE
