### ISSUE TITLE
api.themoviedb.org and thetvdb.com

### ISSUE THREAD

**Issue by MoetaYuko** [gfwlist/gfwlist#2161] opened 2021-10-28 02:48 UTC
DNS spoofing observed with several CN DNS servers, random IP address returned on query:

## api.themoviedb.org
* DNSPod:
```
❯ nslookup api.themoviedb.org 119.29.29.29
Server:         119.29.29.29
Address:        119.29.29.29#53

Non-authoritative answer:
Name:   api.themoviedb.org
Address: 75.126.215.88
Name:   api.themoviedb.org
Address: 2001::45ab:f40f

❯ nslookup api.themoviedb.org 119.29.29.29
Server:         119.29.29.29
Address:        119.29.29.29#53

Non-authoritative answer:
Name:   api.themoviedb.org
Address: 162.125.32.9
Name:   api.themoviedb.org
Address: 2001::45ab:e10d

❯ nslookup api.themoviedb.org 119.29.29.29
Server:         119.29.29.29
Address:        119.29.29.29#53

Non-authoritative answer:
Name:   api.themoviedb.org
Address: 31.13.83.16
Name:   api.themoviedb.org
Address: 2001::45ab:e50b
```
* AliDNS
```
❯ nslookup api.themoviedb.org 223.5.5.5
Server:         223.5.5.5
Address:        223.5.5.5#53

Non-authoritative answer:
Name:   api.themoviedb.org
Address: 108.160.161.20
Name:   api.themoviedb.org
Address: 2001::b93c:d832

❯ nslookup api.themoviedb.org 223.5.5.5
Server:         223.5.5.5
Address:        223.5.5.5#53

Non-authoritative answer:
Name:   api.themoviedb.org
Address: 185.45.6.103
Name:   api.themoviedb.org
Address: 2001::b33c:c110

❯ nslookup api.themoviedb.org 223.5.5.5
Server:         223.5.5.5
Address:        223.5.5.5#53

Non-authoritative answer:
Name:   api.themoviedb.org
Address: 118.193.240.37
Name:   api.themoviedb.org
Address: 2001::b93c:d832
```

## thetvdb.com

* DNSPod:
```
❯ nslookup thetvdb.com 119.29.29.29
Server:         119.29.29.29
Address:        119.29.29.29#53

Non-authoritative answer:
Name:   thetvdb.com
Address: 103.226.246.99
Name:   thetvdb.com
Address: 2001::4131:4498

❯ nslookup thetvdb.com 119.29.29.29
Server:         119.29.29.29
Address:        119.29.29.29#53

Non-authoritative answer:
Name:   thetvdb.com
Address: 157.240.6.35
Name:   thetvdb.com
Address: 2001::b92d:7a5

❯ nslookup thetvdb.com 119.29.29.29
Server:         119.29.29.29
Address:        119.29.29.29#53

Non-authoritative answer:
Name:   thetvdb.com
Address: 103.214.168.106
Name:   thetvdb.com
Address: 2001::4a56:cad

❯ nslookup thetvdb.com 119.29.29.29
Server:         119.29.29.29
Address:        119.29.29.29#53

Non-authoritative answer:
Name:   thetvdb.com
Address: 192.133.77.197
Name:   thetvdb.com
Address: 2001::1f0d:4031
```

* AliDNS
```
❯ nslookup thetvdb.com 223.5.5.5
Server:         223.5.5.5
Address:        223.5.5.5#53

Non-authoritative answer:
Name:   thetvdb.com
Address: 130.211.15.150
Name:   thetvdb.com
Address: 2001::453f:ba1f
```

**Comment by cicku** [comment] 2021-10-30 03:31
Duplicate of #1127

**Closed by cicku** 2021-10-30 03:31 UTC
Labels: DUPLICATE
