### ISSUE TITLE
teddysun.com（秋水逸冰的博客）

### ISSUE THREAD

**Issue by zhangqq008** [gfwlist/gfwlist#1247] opened 2018-09-22 11:23 UTC
this address has been blocked

**Comment by paperbag** [comment] 2018-09-22 11:47
Duplicate of https://github.com/gfwlist/gfwlist/issues/1170

**Comment by cicku** [comment] 2018-09-22 14:01
@paperbag Thank you for marking it as duplicate.

**Closed** 2018-09-22 14:00 UTC
Labels: DUPLICATE
