### ISSUE TITLE
whatsapp text message service has been block 

### ISSUE THREAD

**Issue by s7lx** [gfwlist/gfwlist#733] opened 2017-09-26 02:08 UTC
China telecom \ China Unicom
All of whatsapp ip list is https://github.com/ukanth/afwall/wiki/HOWTO-blocking-WhatsApp

suggestion:
add *.whatsapp.net 
add *.whatsapp.com

**Comment by cicku** [comment] 2017-10-01 01:30
whatsapp.net is already in the list.

**Comment by cicku** [comment] 2018-05-12 00:45
Duplicate of #894

**Closed by cicku** 2018-05-12 00:45 UTC
Labels: DUPLICATE
