### ISSUE TITLE
u2.dmhy.org

### ISSUE THREAD

**Issue by MoeKing** [gfwlist/gfwlist#1483] opened 2019-03-22 06:16 UTC
![](https://i.loli.net/2019/03/22/5c947da98a389.png)
DNS Spoofing

**Comment by wordlesswind** [comment] 2019-03-25 11:20
建议 *.dmhy.org

**Comment by cicku** [comment] 2019-03-25 13:00
Duplicate of #1487

**Closed by cicku** 2019-03-25 13:00 UTC
Labels: DUPLICATE
