### ISSUE TITLE
itunes store international has blocked China Mainland 

### ISSUE THREAD

**Issue by s7lx** [gfwlist/gfwlist#939] opened 2018-03-06 04:07 UTC
itunes store international has blocked China Mainland

e.g. 
https://itunes.apple.com/hk/app/id1329879957 
https://itunes.apple.com/us/app/id1329879957

**Comment by cicku** [comment] 2018-03-17 03:48
Duplicate of #900

**Closed by cicku** 2018-03-17 03:48 UTC
Labels: DUPLICATE
