### ISSUE TITLE
Report websites

### ISSUE THREAD

**Issue by Master-LY** [gfwlist/gfwlist#1075] opened 2018-05-23 11:13 UTC
https://www.binance.com
https://www.huobi.pro/zh-cn/
https://www.bitfinex.com
https://hotbit.io/

All these websites above are crypto-currency related, which are blocked in China.

**Comment by cicku** [comment] 2018-05-23 12:06
Duplicate of #947

**Comment by cicku** [comment] 2018-05-23 12:06
Plus, hotbit.io is not blocked.

**Closed by cicku** 2018-05-23 12:06 UTC
Labels: DUPLICATE, INVALID
