### ISSUE TITLE
Add pixiv.net in to the list Please.

### ISSUE THREAD

**Issue by Co2333** [gfwlist/gfwlist#856] opened 2018-01-04 14:28 UTC
Run `sudo mtr pixiv.net`
![qq20180104-222803](https://user-images.githubusercontent.com/25259084/34567783-9c0eb580-f19e-11e7-851d-0120f18c2e14.png)

**Comment by cicku** [comment] 2018-01-05 01:22
![image](https://user-images.githubusercontent.com/686438/34485876-c12dd56e-f007-11e7-987d-a81db48cb7c7.png)

Duplicate of #718

**Closed by cicku** 2018-01-05 01:22 UTC
Labels: DUPLICATE
