### ISSUE TITLE
please delete  @@||translate.googleapis.com

### ISSUE THREAD

**Issue by benjamin09527** [gfwlist/gfwlist#2302] opened 2022-10-09 09:34 UTC
google翻译 大陆已经被停止了，需要代理

**Comment by yinTang** [comment] 2022-10-13 02:35
+1

**Comment by yinTang** [comment] 2022-10-13 02:36
这几天google翻译都不能用了

**Comment by Linuxer003** [comment] 2022-10-22 04:11
+1

**Comment by Linuxer003** [comment] 2022-10-22 04:13
please delete all rules avoiding proxy to google translate.

**Comment by StrollStars** [comment] 2022-10-23 06:09
https://github.com/gfwlist/gfwlist/issues/2293

**Comment by cicku** [comment] 2022-10-28 14:42
Duplicate of https://github.com/gfwlist/gfwlist/issues/2293

**Closed by cicku** 2022-10-28 14:42 UTC
Labels: DUPLICATE
