### ISSUE TITLE
请求添加 rawgit.com

### ISSUE THREAD

**Issue by 9yu** [gfwlist/gfwlist#685] opened 2017-08-13 11:46 UTC
![qq 20170813194008](https://user-images.githubusercontent.com/5608305/29249346-1faab39a-8060-11e7-9baf-79ef9126ed25.png)
`||rawgit.com`

**Comment by cicku** [comment] 2017-08-13 13:27
Duplicate of #667

**Closed by cicku** 2017-08-13 13:27 UTC
Labels: DUPLICATE
