### ISSUE TITLE
please add https://www.nbcnews.com/ and some others

### ISSUE THREAD

**Issue by 2plus2equals4** [gfwlist/gfwlist#1582] opened 2019-06-06 17:30 UTC
I thought it would've been on the list long ago. But today I wasn't able to visit NBC news in PAC and was able to visit it in Global.

As mraandtux suggested, 
hk01.com
theguardian.com
are blocked.

Also,
washingtonpost.com
has also been blocked, as [reported by Washington Post.](https://www.washingtonpost.com/world/china-adds-washington-post-guardian-to-great-firewall-blacklist/2019/06/08/5ae4fb76-8a56-11e9-b1a8-716c9f3332ce_story.html)

**Comment by mraandtux** [comment] 2019-06-08 11:10
不仅是恩BC，河粉屯和卫报都拿到认证了：
[香港01](https://www.hk01.com/%E5%A4%96%E5%AA%92%E8%A6%96%E9%BB%9E/338262/%E5%85%AD%E5%9B%9B%E4%B8%89%E5%8D%81-%E6%96%99%E8%88%87%E5%A0%B1%E9%81%93%E7%B4%80%E5%BF%B5%E5%85%AD%E5%9B%9B%E6%9C%89%E9%97%9C-%E8%8B%B1%E5%AA%92-%E8%A1%9B%E5%A0%B1-%E8%AD%89%E5%86%8D%E8%A2%AB%E4%B8%AD%E5%9C%8B%E5%B0%81%E9%8E%96)
[卫报](https://www.theguardian.com/world/2019/jun/07/chinese-government-blocks-guardian-website)
GreatFire测试结果：
https://zh.greatfire.org/www.theguardian.com

**Comment by cicku** [comment] 2021-04-20 18:27
Duplicate of #1662

**Closed by cicku** 2021-04-20 18:27 UTC
Labels: DUPLICATE
