### ISSUE TITLE
Add wikiwand.com please ;)

### ISSUE THREAD

**Issue by SenkiTK** [gfwlist/gfwlist#2002] opened 2020-09-16 14:34 UTC
please add "wikiwand.com" to gfwlist , thx 😄️

**Comment by gundaz-aghayev** [comment] 2020-09-25 09:45
#1700

**Comment by codersan2** [comment] 2020-10-18 19:16
Interested.

**Comment by cicku** [comment] 2021-04-19 01:15
Duplicate of #1700

**Closed by cicku** 2021-04-19 01:15 UTC
Labels: DUPLICATE
