### ISSUE TITLE
Please add https://shopee.tw

### ISSUE THREAD

**Issue by Nz666-Kshatriya** [gfwlist/gfwlist#1462] opened 2019-03-04 01:52 UTC
https://shopee.tw  this address is blocked pls add

**Comment by s7lx** [comment] 2019-03-20 13:35
![image](https://user-images.githubusercontent.com/3221213/54688169-1602d380-4b58-11e9-863b-a7fc834a7b62.png)
Make sure  time-out

**Comment by cicku** [comment] 2021-04-20 01:13
Duplicate of #1952

**Closed by cicku** 2021-04-20 01:13 UTC
Labels: DUPLICATE
