### ISSUE TITLE
Plurk

### ISSUE THREAD

**Issue by wordlesswind** [gfwlist/gfwlist#1095] opened 2018-06-11 06:16 UTC
plurk.com
www.plurk.com
s.plurk.com
assets.plurk.com
avatars.plurk.com
emos.plurk.com
images.plurk.com
imgs.plurk.com

Maybe *.plurk.com

**Comment by wordlesswind** [comment] 2018-06-11 06:31
gfwlist/gfwlist#931

**Comment by cicku** [comment] 2018-07-25 02:09
Duplicate of #931

**Closed by cicku** 2018-07-25 02:09 UTC
Labels: DUPLICATE
