### ISSUE TITLE
please remove the config  @@||translate.googleapis.com

### ISSUE THREAD

**Issue by yinTang** [gfwlist/gfwlist#2303] opened 2022-10-13 02:39 UTC
Google  translate has been discontinued  in China

**Comment by StrollStars** [comment] 2022-10-23 06:09
https://github.com/gfwlist/gfwlist/issues/2293

**Comment by cicku** [comment] 2022-10-28 14:41
Duplicate of #2305 2293

**Closed by cicku** 2022-10-28 14:41 UTC
Labels: DUPLICATE
