### ISSUE TITLE
www.artstation.com

### ISSUE THREAD

**Issue by s7lx** [gfwlist/gfwlist#1498] opened 2019-04-01 08:50 UTC
DNS poisoning

ISP:
China Mobile BJ 
China Telecom GD

```
dig www.artstation.com @1.1.1.1   +short
31.13.80.1

dig www.artstation.com @114.114.114.114 +short
88.191.253.157
```

**Comment by cicku** [comment] 2019-04-02 18:44
Duplicate of #1493

**Closed by cicku** 2019-04-02 18:44 UTC
Labels: DUPLICATE
