### ISSUE TITLE
thenation.com and economist.com

### ISSUE THREAD

**Issue by Yu4n** [gfwlist/gfwlist#1326] opened 2018-11-20 09:31 UTC
Both can be pinged but not accessed.

**Comment by paperbag** [comment] 2018-11-21 08:36
`economist.com`：https://github.com/gfwlist/gfwlist/issues/200#issuecomment-208665117
`thenation.com` ：https://github.com/gfwlist/gfwlist/issues/489#issuecomment-278566747 （but not in the list）

**Comment by cicku** [comment] 2018-12-05 17:33
Duplicate of #489

**Closed by cicku** 2018-12-05 17:33 UTC
Labels: DUPLICATE
