### ISSUE TITLE
www.chinatimes.com 部分http页面屏蔽，数量较多，请求添加http整站

### ISSUE THREAD

**Issue by Toxic-Cat** [gfwlist/gfwlist#1022] opened 2018-04-24 19:04 UTC
example: 
http://www.chinatimes.com/cn/newspapers/20170126000683-260301
http://www.chinatimes.com/cn/realtimenews/20170129001658-260407
http://www.chinatimes.com/cn/realtimenews/20170129001902-260405

浙江电信
ERR_CONNECTION_ABORTED

**Comment by houbaron** [comment] 2018-04-28 13:44
可以用 HTTPS，Chrome 有个插件叫 HTTPS Everywhere．

**Comment by cicku** [comment] 2019-07-14 23:33
Duplicate of #977

**Closed by cicku** 2019-07-14 23:33 UTC
Labels: DUPLICATE
