### ISSUE TITLE
downloader.disk.yandex.ru

### ISSUE THREAD

**Issue by qwerttvv** [gfwlist/gfwlist#2320] opened 2022-11-18 03:54 UTC
https://dig.ping.pe/downloader.disk.yandex.ru:A:8.8.8.8

![image](https://user-images.githubusercontent.com/56712217/202613141-c010481e-ce9b-4828-8b66-782020ea138a.png)

**Comment by cicku** [comment] 2023-02-08 04:27
Duplicate of #2343

**Closed by cicku** 2023-02-08 04:27 UTC
Labels: DUPLICATE
