### ISSUE TITLE
Discord and Google drive should be added into gfwlist

### ISSUE THREAD

**Issue by BrunoJu** [gfwlist/gfwlist#1955] opened 2020-05-19 15:15 UTC
Hi,

I used discord APP and Google Drive Client in my workspace and I think these two websites as below should be added into gfwlist:

https://discord.com/
https://drive.google.com

Thanks a lot.
BR

**Comment by cicku** [comment] 2020-07-17 21:06
Duplicate of #1960

**Closed by cicku** 2020-07-17 21:06 UTC
Labels: DUPLICATE, FIXED
