### ISSUE TITLE
themoviedb相关域名

### ISSUE THREAD

**Issue by ArthurSmoke** [gfwlist/gfwlist#1919] opened 2020-03-13 07:21 UTC
api.themoviedb.org
www.themoviedb.org
image.tmdb.org

**Comment by ClwonLoon** [comment] 2020-03-15 15:34
+1

**Comment by bluehr** [comment] 2021-05-08 03:07
++++1

**Comment by s7lx** [comment] 2021-11-02 03:16
@cicku duplicated

**Comment by cicku** [comment] 2021-11-02 14:02
Duplicate of #1127

**Closed by cicku** 2021-11-02 14:02 UTC
Labels: DUPLICATE
