### ISSUE TITLE
Reddit is blocked now

### ISSUE THREAD

**Issue by marikid** [gfwlist/gfwlist#1184] opened 2018-08-13 14:32 UTC
Great Fire Analyzer: https://zh.greatfire.org/https/www.reddit.com
Related Post:
TechNews: http://technews.tw/2018/08/13/reddit-is-finally-ban-in-china/
Reddit: https://www.reddit.com/r/saraba1st/comments/965szz/%E7%8E%B0%E5%9C%A8%E8%A2%AB%E5%A2%99%E4%BA%86/

**Comment by wordlesswind** [comment] 2018-08-13 21:18
#1183 
Duplicate issue

**Comment by cicku** [comment] 2018-08-13 23:50
Duplicate of #1183

**Closed by cicku** 2018-08-13 23:50 UTC
Labels: DUPLICATE

**Comment by idealclover** [comment] 2018-08-14 06:59
@marikid lol, I just saw the duplication and closed the issue.
