### ISSUE TITLE
pixiv.com  can connect directly,please remove it from gfwlist

### ISSUE THREAD

**Issue by w7yuu** [gfwlist/gfwlist#1665] opened 2019-08-08 02:54 UTC
pixiv.com  can connect directly,please remove it from gfwlist

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by Cat7102** [comment] 2019-08-13 12:53
I can't connect it without vpn.

**Comment by cicku** [comment] 2021-04-20 22:08
Duplicate of #1236

**Closed by cicku** 2021-04-20 22:08 UTC
Labels: DUPLICATE
