### ISSUE TITLE
add chromeba.net

### ISSUE THREAD

**Issue by lovezhumeimei** [gfwlist/gfwlist#1693] opened 2019-09-08 15:13 UTC
chromeba.net
DNS spoofing

**Comment by tomac4t** [comment] 2019-09-10 12:59
Duplicate of https://github.com/gfwlist/gfwlist/issues/1656

**Comment by cicku** [comment] 2023-01-09 04:04
Duplicate of https://github.com/gfwlist/gfwlist/issues/1656

**Closed by cicku** 2023-01-09 04:04 UTC
Labels: DUPLICATE
