### ISSUE TITLE
Please add 'softs.wtf'.

### ISSUE THREAD

**Issue by Sam0230** [gfwlist/gfwlist#1323] opened 2018-11-18 08:03 UTC
Please add 'softs.wtf'. We can not access it in mainland China.

**Comment by zao123h** [comment] 2018-11-19 07:31
I just prepared to submit and found that someone has submitted it, I hope the author will update as soon as possible.

**Comment by cicku** [comment] 2018-12-05 17:43
Duplicate of #1262

**Closed by cicku** 2018-12-05 17:43 UTC
Labels: DUPLICATE

**Comment by cicku** [comment] 2018-12-05 17:46
I cannot access this domain, would you please tell me how to access it? Is it now `wget.shop`?
