### ISSUE TITLE
Please add archiveofourown.org

### ISSUE THREAD

**Issue by alphazhao** [gfwlist/gfwlist#1907] opened 2020-02-29 14:22 UTC
archiveofourown.org was banned at 2020-2-29

https://zh.greatfire.org/https/archiveofourown.org

![image](https://user-images.githubusercontent.com/22046855/75609403-30ed0e80-5b43-11ea-9a88-b5b96f7335c5.png)

**Comment by ZirealCirilla** [comment] 2020-03-01 02:36
哇动作好快，昨天晚上都懵逼去了，今天早上才想起来

**Comment by mraandtux** [comment] 2020-03-02 01:45
补加封锁方式：DNS污染+SNI重置
（某X姓艺人粉附全责）

**Comment by cicku** [comment] 2020-07-17 21:44
Duplicate of #1935

**Closed by cicku** 2020-07-17 21:44 UTC
Labels: DUPLICATE
