### ISSUE TITLE
wikipedia related

### ISSUE THREAD

**Issue by zzzgit** [gfwlist/gfwlist#1872] opened 2020-02-03 10:55 UTC
![image](https://user-images.githubusercontent.com/1060733/73647448-72121000-46b6-11ea-82e1-01d4d79c8d2b.png)

Why is the stuff about Wikipedia commented?
It's now banned in China, we need to uncomment it.

**Comment by cicku** [comment] 2021-04-19 01:56
Duplicate of #1811

**Closed by cicku** 2021-04-19 01:56 UTC
Labels: DUPLICATE
