### ISSUE TITLE
raw.githubusercontent.com早就被维尼拉清单了

### ISSUE THREAD

**Issue by yu-chenxi** [gfwlist/gfwlist#1962] opened 2020-06-06 14:05 UTC
* *原因是`DNS pollution`, 建议加入*

**Comment by lolPlatinumPlayer** [comment] 2020-06-17 12:18
raw.githubusercontent.com好像已经被作者放进列表了，但是camo.githubusercontent.com没有

**Comment by firefoxwang** [comment] 2020-06-29 15:56
GFWList URL(Github): https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

Notwithstanding Github is competent for distribution, to hedge outages or connection issues we still recommend using any URL below.

Official mirror URLs:

Pagure: https://pagure.io/gfwlist/raw/master/f/gfwlist.txt

Repo.or.cz: http://repo.or.cz/gfwlist.git/blob_plain/HEAD:/gfwlist.txt

Bitbucket: https://bitbucket.org/gfwlist/gfwlist/raw/HEAD/gfwlist.txt

Gitlab: https://gitlab.com/gfwlist/gfwlist/raw/master/gfwlist.txt

TuxFamily: https://git.tuxfamily.org/gfwlist/gfwlist.git/plain/gfwlist.txt

**Comment by yu-chenxi** [comment] 2020-06-30 12:54
@firefoxwang 
We do not only use the wildcard URL `raw.githubusercontent.com/*` to update/sync gfwlist.txt. We can also use it to download some script.

**Comment by cicku** [comment] 2020-07-17 21:50
Duplicate of #1860

**Closed by cicku** 2020-07-17 21:50 UTC
Labels: DUPLICATE
