### ISSUE TITLE
request to add *.wikimedia.org

### ISSUE THREAD

**Issue by dongzhuoer** [gfwlist/gfwlist#2088] opened 2021-04-08 00:20 UTC
wikipedia website refers to many contents from en.wikimedia.org

**Comment by cicku** [comment] 2021-04-16 15:35
Duplicate of #2060

**Closed by cicku** 2021-04-16 15:35 UTC
Labels: DUPLICATE

**Comment by dongzhuoer** [comment] 2021-06-06 01:19
Can't connect to en.wiktionary.org, such as <https://en.wiktionary.org/wiki/%E6%9A%91>

**Comment by cicku** [comment] 2021-06-06 01:43
Please do not reply old issues.
