### ISSUE TITLE
New Blocked Website in Mainand China

### ISSUE THREAD

**Issue by alex-nagami** [gfwlist/gfwlist#1484] opened 2019-03-22 13:39 UTC
New Blocked website:
https://www.artstation.com/
https://potplayer.daum.net/

**Comment by alex-nagami** [comment] 2019-03-22 13:40
Please Add it ,thanks!

**Comment by shoakepei** [comment] 2019-03-25 08:52
https://www.artstation.com/ Please

**Comment by cicku** [comment] 2019-04-02 18:48
Duplicate of #1409 and #1493

**Closed by cicku** 2019-04-02 18:48 UTC
Labels: DUPLICATE
